<!-- ENG -->
# Exercises in Fundamentals of Data Science / Exercises in Fundamentals of Artificial Intelligence - Introduction to Python ①


※Distribution or redistribution of these practice materials without the copyright holder's permission is not permitted.

<!-- ENG -->
　(These materials are created based on the [Chainer Tutorial](https://tutorials.chainer.org/ja/02_Basics_of_Python.html), with summaries and additions. I would like to thank the authors for allowing us to use their materials.)

　In this chapter, we will learn the basics of the programming language Python. If you want to learn more precise and detailed knowledge, please refer to [the official Python tutorials](https://docs.python.jp/3/tutorial/index.html).

　Note that this course assumes the use of **Python 3**. Some parts of the code are not compatible with Python 2, so you should also pay attention to the Python version when getting the code from the Internet (**S1**).

<!-- ENG -->
## 1 | Python Features

　Python is the most commonly used programming language in the field of data analysis and machine learning. It has a wide range of libraries suitable for machine learning and other applications, such as pandas, scikit-learn, and PyTorch, which we will be using herein. Compared to languages such as C, which is one of the most well known programming language, Python does not require the program to be converted (compiled) into a format that is understood by a computer before execution, making trial and error easier. This is probably another reason why Python is widely used in the field of data analysis and machine learning.

<!-- ENG -->
## 2 | Syntax

　The first step in programming is to learn the **syntax**, which are the rules for communicating instructions to the computer.
If a program has a description that ignores syntax, the computer will not be able to interpret the meaning, and even if it is executed, an error will occur and the process will stop. Therefore, the syntax needs to be well understood.


　In this article, I will focus on the following elements.

- Variables
- Arithmetic operators
- Arrays
- Dictionaries
- Control statements
- Functions

<!-- ENG -->
### 2.0 | Before writing the program

　Use only English letters (lowercase/uppercase), numbers, and just some specific symbols in the program. **In principle, do not use Japanese characters**. In particular, **take care to ensure you absolutely do not use double byte spaces, as they are a big problem and create a troublesome situation in which the program does not work and the cause is difficult to understand; it is not easy to visually distinguish between double byte spaces and two single byte spaces.**

In [4]:
# Example where there is double byte and single byte spaces (see also Supplementary Material S2)
# There is a double byte space before “2”

1+2

3

<!-- ENG -->
### 2.1 | Variables

　**A variable** is **storage area that has a name** in which various values can be stored. By storing and updating values in these variables, the results of calculations can be temporarily held.

<!-- ENG -->
　Let's try **assigning** a value of `1` to a variable named `a`.

In [ ]:
a = 1

<!-- ENG -->
　Use the `=` symbol for substitution. The `=` symbol is confusing because it means equal in mathematics, but in Python it means **”assign the value on the right side to the variable on the left side"**.

<!-- ENG -->
　**A function** called `print()` is used as a way to check the value stored in a variable.

In [ ]:
print(a)

In [ ]:
print(a + 3)

<!-- ENG -->
　The name given to a variable can be freely decided by the person writing the code.
However, **it is very important to give it a name that is easy to understand**.
Giving it a name that is easy to understand will be **a big help for others who read your code as well for you to understand the code a week or month later**.

<!-- ENG -->
### 2.2 | Comments

　In Python, all strings between the `#` (hash mark) and the end of the line are ignored.
The part that follows the `#` is called a **comment**.
Comments are often used in code to convey the meaning of variables and processes to the reader of the code. Even though Japanese (and other any languages) can be used in Google Colab, it is not recommend to use them because **there may be cases where comments in other languages generate errors** while running Python on your local computer.

　As a test, try to run the cell below. Although the `print()` function is provided in the code, since it is commented out, it is not executed and nothing is printed out.

In [ ]:
# This line and the line below it are commented out and will be ignored at runtime.
# print(a)

<!-- ENG -->
### 2.3 | Numeric data types: Integers and floating-point numbers

　In Python, there are two ways to represent numbers: **integers (abbreviated as `int`)** and **floating-point numbers (abbreviated as `float`)**.

In [ ]:
var_i = 1   # integers
var_f = 1.5 # floating-point numbers

<!-- ENG -->
### 2.4 | Arithmetic operators

　In this next section, we will learn about **operators**. You may not be familiar with this word, but it means `+` for addition and `-` for subtraction. Python defines a variety of operators, but the most commonly used are called **arithmetic operators**, as shown below.

| Operators | Symbol |
|------|------|
| Addition | `+`  |
| Subtraction | `-`  |
| Multiplication | `*`  |
| Division | `/`  |
| Floor division   | `//` |
|  Modulus　        | `%`  |
| Exponentiation           | `**` |

　Many of these operators are familiar, while others use slightly special symbols such as exponentiation `**`. Let's understand how to use it by looking at specific examples.

In [ ]:
a = 1
b = 3
print(a + b)  # It is common to put one single byte character space on each side of the operator.

In [ ]:
a = 2
b = 3
c = a + b # You can also assign the result of an operator to a variable.
print(c)

In [ ]:
print(5 / 2) # Floating-point values are output

In [ ]:
print(5 // 2) # The quotient of 5 divided by 2 is then output as an integer value.

In [ ]:
print(5 % 2) # The remainder of 5 divided by 2 is output.

In [ ]:
print(2 ** (0.5)) # 2 to the 0.5th power, or the square root of 2

<!-- ENG -->
　What happens when you calculate something that is not defined using normal arithmetic operators? As a test, try dividing 1 by 0.

In [ ]:
a = 1
b = 0
print(a / b)

<!-- ENG -->
　An error is generated. **Let's look at the Error details**.
First of all, there is a description called `ZeroDivisionError`, which indicates that this is an error corresponding to the operation "divide by zero".
Next, there is an arrow indicated in the third line of the code. It appears that an error occurred on line 3.
In this way, you can know **what kind of error** is occurring and **where** from the error display.

　In the case of Google Colaboratory, the `SEARCH STACK OVERFLOW` button is also displayed. This is a shortcut button to search stackoverflow, which is like Yahoo! Answers of the programming world, and is **a unique feature of Google Colab**. This may be useful when investigating the cause of an error.
In Supplementary Material **S2**, we have compiled a list of common errors, which you can also refer to.

-------

<!-- ENG -->
##### Exercise 1 (not required to submit)
　Assign `201` to the variable `x` and `9` to the variable `y`, and output the following results respectively.

1. `x + y`
2. `x - y`
3. `x * y`
4. `x / y`
5. `x // y`
6. `x % y`
7. `x ** y`

-------

<!-- ENG -->
### 2.5 | Augmented assignment statement

　Then there is another group, `+=` and `-=`, which are often used.
These are a combination of operators and assignment statements, and are called **augmented assignment statements**.

As shown below, `+=` **updates the variable on the left side with the result of adding the value on the right side to the variable on the left side**. The following two examples are the same.

In [ ]:
# When not using augmented assignment statements
count = 0
count = count + 1
print(count)

In [ ]:
# When using augmented assignment statements
count = 0
count += 1
print(count)

<!-- ENG -->
### 2.6 | Strings

　So far, we have stored numerical values as variables and processed them, but we can also store text in variables.
Enclosing the target string in single quotation marks `' '` or double quotation marks `" "` distinguishes it from variables and numbers.

In [ ]:
s = "Tokyo Tech"
print(s)

In [ ]:
s = 'Tokyo Institute of Technology'
print(s)

In [ ]:
s = '777'
print(s)

<!-- ENG -->
　If you want to store a multi-line string in a variable, use three quotation marks in a row.

In [ ]:
s = """Apple
Banana
Cherry"""
print(s)

<!-- ENG -->
　Two strings can be combined using the arithmetic operator `+`.

In [ ]:
s1 = "Tokyo"
s2 = "Tech"
print(s1 + s2)       # No single byte space
print(s1 + " " + s2) # Added single byte space

<!-- ENG -->
　Numbers and strings **can't** be put together as they are. When running the following code, a `TypeError` error results and "must be str, not int" is output. This means (since there is nothing underlined, it's challenging to discern) that only strings (= "must be str") <u>are allowed to be added to strings (`str`)</u>, and integers (`int`) are not allowed.

In [ ]:
s = "Galaxy Express"
i = 999
print(s + i)

<!-- ENG -->
　What should I do? From the previous error message, we know that **string + integer is not allowed**. On the other hand, **string + string is fine**. Therefore, we will use the `str()` function to convert a **numeric** value into a **string** value before combining with the strings. This operation of converting the type of variable is called **casting**.

In [ ]:
s = "Galaxy Express"
i = 999
print(s + str(i))

<!-- ENG -->
　Alternatively, it is also possible to combine text strings and numbers by using special text strings called "formatted string literals", commonly known as **f-strings**.

In [ ]:
s = "Galaxy Express"
i = 999
print(f"{s} {i}")                 # Place the text string "f" before the quotation mark and wrap the variable name with {}.
print(f"There is a novel called {s} {i}.") # The part not enclosed in {} will be output as is.

<!-- ENG -->
　It is also possible to use operators within this f-string.

In [ ]:
s = "Galaxy Express"
i = 999
print(f"There is no novel called {s} {i*2}.") # Perform multiplication in {}

<!-- ENG -->
　Finally, we will introduce two useful functions for text string processing.

　First, we can see the length of the string by applying the built-in function `len()` to the string.

In [ ]:
print(len("Tokyo Tech"))
print(len("Tokyo Institute of Technology"))

<!-- ENG -->
　Next, the `split()` function can be used to convert a single string, `"Tokyo,Osaka,Kyoto"`, into a list using a comma as a separator. (We will learn about lists in the next section)

In [1]:
s = "Tokyo,Osaka,Kyoto"
print(s.split(",")) # Separate using a comma as a separator

['Tokyo', 'Osaka', 'Kyoto']

In [ ]:
s = """
Apple  Ringo
Banana Banana
Cherry Sakuranbo
"""
print(s.split()) # Separate using spaces or line breaks as a separator

<!-- ENG -->
### 2.7 | Arrays: Lists and tuples

　Up to this point, we have only dealt with the case of assigning a single value to a single variable, such as `a = 1`. However, we can also express a single element with multiple values, such as coordinates in three-dimensional space.
In such a case, we can introduce the **array**, which arranges multiple values in a single column like a vector.

　In Python, arrays can be represented in two different ways: **lists** and **tuples**. Lists and tuples can be handled almost in the same way, **but there is difference whether or not elements can be edited and or added, etc**. We will check this by actually running Python code.

<!-- ENG -->
　First of all, let's create one list and one tuple.

In [5]:
lst = [1, 2, 3, 4] # When creating a list: Enclose multiple elements with "[]".
tup = (5, 6, 7, 8) # When creating a tuple: Enclose multiple elements with "()".
print(lst)
print(tup)

[1, 2, 3, 4]
(5, 6, 7, 8)

<!-- ENG -->
　It is also possible to include lists and tuples as list and tuple elements.

In [6]:
list_of_everything = [[1, 2, 3], (4, 5, 6, 7), 8, "nine"]
print(list_of_everything)

[[1, 2, 3], (4, 5, 6, 7), 8, 'nine']

<!-- ENG -->
　Next, try to extract the elements in a list or tuple. In Python, the elements of an array are counted from the leftmost position: **0**, 1st, 2nd, and so on. Therefore, if you want to get the leftmost element, you have to write code **to get the element in the 0 position**.

In [7]:
lst = [1, 2, 3, 4]
tup = (5, 6, 7, 8)
print(lst[0])      # Get lst element (1) that is in the 0 position
print(tup[2])      # Get tup element (7) that is in the 2nd position

1
7

<!-- ENG -->
　Next, let's try a **slice** operation to extract multiple elements at a time from the list.
The slice gets the elements of the half-open interval $0 \leq x < 2, x\in\mathbb{Z}$ when the index is specified as a range using a colon `:` as in `0:2` (In other words, get the elements beginning from the start position **to the one before the end position**.)

In [8]:
lst = [1, 2, 3, 4]
tup = (5, 6, 7, 8)
print(lst[0:2])    # Get lst 0 and 1st position elements
print(tup[1:4])    # Get tup 1st, 2nd, and 3rd elements

[1, 2]
(6, 7, 8)

<!-- ENG -->
　When using the slice operation, it is possible to omit the index in the following two cases.
* If the starting position is the first in the array
* If the end position is the last in the array

In [9]:
lst = [1, 2, 3, 4]
tup = (5, 6, 7, 8)
print(lst[:2])    # Get lst 0 and 1st position elements
print(tup[1:])    # Get tup 1st, 2nd, and 3rd elements
print(tup[:])     # Get tup 0, 1st, 2nd and 3rd position elements

[1, 2]
(6, 7, 8)
(5, 6, 7, 8)

<!-- ENG -->
　This slicing operation can also be used to get elements by skipping one element, or to get elements in reverse order. (Especially the `[::-1]` operation, which is often used)

In [10]:
lst = [1, 2, 3, 4, 5]
tup = (6, 7, 8, 9, 10)
print(lst[::2])   # Get the first and every 2nd element of lst.
print(tup[::-1])  # Get each element in reverse order from tup.

[1, 3, 5]
(10, 9, 8, 7, 6)

<!-- ENG -->
　If you want to know the number of elements in a list or tuple, use the built-in ` len()` function, just like for strings.

In [11]:
lst = [1, 2, 3, 4]
tup = (5, 6, 7)
print(len(lst))
print(len(tup))

4
3

In [ ]:
lst = ["Apple", "Banana", "Cherry"]
print(len(lst)) # Returns the number of elements in the list instead of the length of the string.

<!-- ENG -->
　Next, try changing the list and tuple elements.

In [ ]:
lst = [1, 2, 3, 4]
lst[0] = 100      # Replace the lst 0 position element with 100
print(lst)

In [ ]:
tup = (1, 2, 3, 4)
tup[0] = 100      # Replace the tup 0 position element with 100
print(tup)

<!-- ENG -->
　On the one hand, while we are able to modify the elements in the list, the tuple gave the error `TypeError: 'tuple' object does not support item assignment`. In this way, **tuples are restricted so that their values cannot be rewritten later.**

　The next step is to add the elements, which can be done only on the list.

In [ ]:
lst = [1, 2, 3, 4]
lst.append(100)     # Add the element 100 to the end of the lst
print(lst)

In [ ]:
tup = (1, 2, 3, 4)
tup.append(100)
print(tup)

<!-- ENG -->
　The error string for the tuple is different from the previous one: `AttributeError: 'tuple' object has no attribute 'append'`.

<!-- ENG -->
　Finally, an **empty list** can be defined and used to add new elements as needed in the later stages of the process.

In [ ]:
# Defining an empty list
array = []

# Adding elements to an empty list
array.append('Tokyo')
array.append('Tech')

print(array)

---------

<!-- ENG -->
##### Exercise 2 (not required to submit)

　For the points $\boldsymbol{x}, \boldsymbol{y}$ in the following two-dimensional space, calculate the Euclidean distance between the two points.

(Do the calculations by hand as well to make sure the result is correct)

```py
x = (1,5)
y = (5,2)
```

---------

<!-- ENG -->
##### Exercise 3 (not required to submit)
　For the points $\boldsymbol{x}, \boldsymbol{y}$ in the following four-dimensional space, calculate the Euclidean distance between the two points. (The answer should be $\sqrt{13} \fallingdotseq 3.60555$)

```py
x = [5, 4, 10, 4]
y = [3, 2, 8, 3]
```

---------

<!-- ENG -->
### 2.8 | Dictionaries (`dict`)

　With the arrays (lists, tuples) introduced previously, it is possible to handle multiple values together.
Let's think about how to summarize the results of the regular tests.
For example, if the result of a score of 90 in math, 75 in science, and 80 in English is represented as a list with `scores = [90, 75, 80]`, it is not obvious **which score corresponds to which subject**.

　Python's `dict` type is useful when the order of the elements is not self-evident, or when it is important to know what information is in each value. The `dict` type stores a **key** and its corresponding **value** as a set.

In [ ]:
# Defining a dictionary
scores = {'Math': 90, 'Science': 75, 'English': 80 }
print(scores)

<!-- ENG -->
In the above example, English, Math, and Science are the keys, and the scores 80, 90, and 75 are the values corresponding to each key.

<!-- ENG -->
　To retrieve elements of a dictionary, use `[ ]` the same as with lists and tuples, and indicate a key in `[ ]` to retrieve the corresponding value.

In [ ]:
# The key accesses the value of Math
print(scores['Math'])

<!-- ENG -->
　As you can see from the explanations so far, in order to retrieve an element of the dictionary, you need to know in advance **what keys exist**. Also, there are times when you want to **get all the values** without the keys, such as when you want to calculate the average score. In such a case, the following functions (methods) for `dict` type can be used.

- `keys()`\: Retrieves a key array. Returns an object type called `dict_keys` that has similar characteristics to a tuple.
- `values()`\: Retrieves an array of values. Returns an object type called `dict_values` that has similar characteristics to a tuple.
- `items()`\: Retrieves an array of `(key, value)` tuples for each element. Returns an object type called `dict_items` that has similar characteristics to a tuple.

Note that `dict_keys`, `dict_values`, `dict_items` are object types specific to the dictionary type, and strictly speaking they are different from standard tuples, but it is safe to say they are object types with similarities to tuples.

In [ ]:
# Defining a dictionary
scores = {'Math': 90, 'Science': 75, 'English': 80 }

In [ ]:
# A list of keys
keys = scores.keys()
print(keys)

In [ ]:
# A list whose elements are tuples (key, value)
elements = scores.items()
print(elements)

<!-- ENG -->
　The next step is to add or update the elements. First, to add an element to the dictionary, specify a new key and assign a value to it.

In [ ]:
# Defining a dictionary
scores = {'Math': 90, 'Science': 75, 'English': 80 }

In [ ]:
scores['Language Arts'] = 85 # Add the element

In [ ]:
print(scores)

<!-- ENG -->
　Next, the value is updated (overwritten) by specifying a key that already exists and performs a substitution.

In [ ]:
# Defining a dictionary
scores = {'Math': 90, 'Science': 75, 'English': 80 }

In [ ]:
scores['Math'] = 95

In [ ]:
print(scores)

<!-- ENG -->
### 2.9 | Control statements

　If you want to write a complex program, you will need a process that repeats itself or changes its behavior depending on conditions. These are described using **control statements**, and here we will introduce two of the most basic control statements.

- Looping (`for`, `while`)
- Conditional branch (`if`)

In Python, these consist of two parts called a **header** and a **block**, which together are called a **compound statement**.

<!-- ENG -->
<img src="https://i.imgur.com/ORUccmf.png" width=500>

<!-- ENG -->
　As shown in the figure above, in a control statement, `for`, `if`, and so on, are written in the header line, followed by the `:` symbol at the end of the line, and then a series of process statements to be executed under the conditions in the header line are written as a block in the next line and thereafter (this form of statement is called "syntax").

　A block is represented by inserting empty space characters, called an **indent**, at the beginning. Sentences **indented with the same number of single byte spaces** are considered to be a block. In addition, Google Colaboratory and text editors for programming (Emacs, Vim, VSCode, etc.) will automatically insert the specified number of single byte spaces when you use the **Tab key**, which is good to use.

　The number of single byte spaces used to represent indentation should be standardized to two or four. Since Google Colaboratory is set to use two single byte spaces, this course will use this setting.

<!-- ENG -->
### 2.10 | Conditional branch (`if` statement)

　The `if` statement is used to change the process depending on whether the specified condition is `True` or `False`. The syntax of the `if` statement is shown below.

<!-- ENG -->
<img src="https://i.imgur.com/9cJoqkK.png" width=500>

<!-- ENG -->
#### Comparison operators

　When using `if` statements, it is important to have a way to express the "condition". The **comparison operator** is an operator that compares two values and outputs a boolean value of the described comparison (in the form of a variable indicating whether the comparison is `True` or `False`).

| Operators | Symbol |
|------|------|
| Less than | `<` |
| Greater than | `>` |
| Less than or equal to | `<=` |
| Greater than or equal to | `>=` |
| Equal | `==` |
| Not equal | `!=` |

The following are examples of calculations for some comparison operators.

In [ ]:
print(1 < 2)
print(2 == 5)
print(1 != 2)
print(3 >= 3)

In [ ]:
print('Material' == 'Material')
print('Material' == 'material')

In [ ]:
print([1,2] == [1,2])
print([1,2] != [1,3])
print([1,2] == (1,2)) # Lists and tuples are interpreted as different data
print([1,2] != (1,3))

<!-- ENG -->
　Also, remember the `not` statement reverses the boolean value. `not True` returns `False`, and `not False` returns `True`.

In [12]:
print(not True)
print(not False)

False
True

In [13]:
# The following two are equivalent

print(not 1 == 2)
print(1 != 2)

True
True

<!-- ENG -->
　Lastly, this example shows how to use `and` as well as `or`, which combines two boolean values. The following is a table of input/output relationships (truth table). We will have a look at some of them in the actual code.

| `x` | `y` |→| `x and y` | `x or y` |
|----|----||----|----|
| `True` | `True` |→| `True` | `True` |
| `True` | `False` |→| `False` | `True` |
| `False` | `True` |→| `False` | `True` |
| `False` | `False` |→| `False` | `False` |

In [ ]:
x = 1
print(x < 0)
print(x > 0)
print(x < 0 or x > 0)

In [ ]:
x = 1
y = 2
z = 3
print(x < y)
print(y < z)
print(x < y and y < z) # x < y < z

<!-- ENG -->
#### `if` statement
　Let's start by writing the simplest `if` statement, which consists of only `if`. Let's check the behavior of the following code while changing the value of `a`. The string will be printed (`print()` function) only if `a` is greater than zero, otherwise nothing is supposed to be printed.

In [ ]:
a = 0

if a > 0:
  # Indent here
  print('Greater than 0')

<!-- ENG -->
Next, check the behavior of the following two codes that use `elif` and `else`, while changing the value of `a` in the same way.

In [ ]:
a = 1

if a > 0:
  print('Greater than 0')
else:
  print('Less than or equal to 0')

In [ ]:
a = 0

if a > 0:
  print('Greater than 0')
elif a == 0:
  print('equal to 0')
else:
  print('less than 0')

------

<!-- ENG -->
##### Exercise 4 (not required to submit)

　Randomly create integers between 0 and 50, and **use the `print()` function to print `"EVEN"` if the remainder of the integer divided by 2 is 0, and `"ODD"` if the remainder is not 0**.
The code for assigning the created integer to `rand_int` is written below. Use it to write the rest of the code.

In [ ]:
import random

# Create a random number between 0 and 50
rand_int = random.randint(0, 50)
print(f"rand_int is {rand_int}")

# Write the rest of the code below to output the string

-------

<!-- ENG -->
### 2.11 | Looping (`for` statement)

　Next, let's use the `for` statement, which is a control statement that describes a looping process. The following example is a program that calculates the sum of the values in an array.

In [ ]:
lst = [1.5, 3, 100]
total = 0
for number in lst:
  print(number)
  total += number
print("total value is", total)

<!-- ENG -->
As shown above, the elements of the array written after `in` are assigned to `number` one by one.

　In order to keep track of the number of iterations, the `for` statement often uses an array with a sequence of numbers starting from 0 and increments by 1, which can be created using the `range()` function (Technically, it's ‘kind of’ an array, but I'll spare you the details here).

In [ ]:
for i in range(5): # range(5) creates something like [0, 1, 2, 3, 4]
  print(i)

<!-- ENG -->
For such variables whose values increase by one, it is customary to use one letter variable names such as `i`, `j`, `k`, etc.

　Using the `range()` function, the `for` statement that was described earlier can be rewritten as follows.

In [ ]:
lst = [1.5, 3, 100]
total = 0
for i in range(len(lst)): # len(lst) is a built-in function that returns the length of an array
  print(lst[i])
  total += lst[i]
print("total value is", total)

<!-- ENG -->
　It is also possible to use a `for` statement within a `for` statement, or an `if` statement within a `for` statement, etc. (The same applies to `while` statements and functions, which will be explained later. A new compound statement can be placed inside a compound statement block.) In this case, the block is indented further.

In [ ]:
size = 5
count = 0
for i in range(size):
  # Indent
  for j in range(i+1,size): # Create something like an array of integer values from a up to, but not including, b with range(a,b)
    # Indent further
    print(i,j)
    count += 1
print(f"{size}C2 = {count}")

<!-- ENG -->
### 2.12 | Looping (`while` statement)

　In addition to `for`, loop processes can also be written using `while`.
With the `while` statement, instead of specifying an array, specify the **condition for continuing the loop**.
As long as the specified conditional statement is `True`, the process described in the block part is repeatedly executed.

In [ ]:
count = 0

while count < 3:   # while condition:
  print(count)
  count += 1

<!-- ENG -->
The variable `count` that is used here counts the number of times the content of the loop has been executed. First of all, it is initialized with `0`, and then 1 is added to the `count` value each time the process in the loop is performed. The conditional expression using `count` is given to the `while` statement to specify the number of times the loop should run.

<!-- ENG -->
　By using `not` as explained earlier, you can also write a process that repeats the loop while the specified condition is **not** met. In the following example, `num` is decremented by 1 unless `num==2` is satisfied.

In [ ]:
num = 10
while not num == 2:
  print(num)
  num -= 1

<!-- ENG -->
　As explained in “How to use Google Colaboratory”, the `while` statement can become a code that never ends (sometimes called an infinite loop). If you have accidentally executed a code such as the following, you can press the stop button displayed on the left side of the code block.

In [ ]:
# Infinite loop example: Press the stop button ■ on the left to force a stop
count = 0
while count >= 0:
  count += 1

-------

<!-- ENG -->
##### Exercise 5 (not required to submit)

For points `x`, `y` in the following 20-dimensional space, calculate the Euclidean distance between the two points.

```
x = [5, 4, 10, 4, 8, 4, 6, 8, 5, 4, 6, 5, 9, 9, 5, 7, 1, 1, 5, 8]
y = [3, 2, 8, 3, 4, 10, 10, 2, 4, 2, 3, 9, 8, 1, 3, 6, 5, 3, 9, 2]
```
-----

<!-- ENG -->
### 2.13 | Functions
　When you write your own code, if you write a set of processes, it is often convenient to put together the code for that process so that it can be reused from various parts of the entire program. In this section, we will introduce the method of defining a **function** as a way of grouping processes together.

<!-- ENG -->
#### Define a function

　Functions also have a **header** and a **block**, just like the control statements.

<!-- ENG -->
<img src="https://i.imgur.com/snSc5OV.png" width=500>

<!-- ENG -->
In the following, we are creating **the function `double()` that doubles the received value**. Note that **a function is not executed just by defining it.**

In [ ]:
# Defining the function double()
def double(x):
  return 2 * x

<!-- ENG -->
The defined function can be executed (in the same way as `print()` function, etc.) as follows.

In [ ]:
# Executing the function double()
print(double(1))

number = double(1.2)
print(number)

<!-- ENG -->
The variable or value passed to a function, such as `x` in `double(x)`, is called an **argument**, and the output of the function is called the **return value**.

　In the following, the types of variables that can be used as arguments are changed, increasing or decreasing the number of arguments, and creating functions that have no return value. Try actually executing the function to see how it behaves by using `print()`, etc.

In [ ]:
def plus(a, b): # 2 arguments
  return a + b

x = 1
y = 10
print(plus(x, y)) # 1 + 10

z = 3
result = plus(x, z) # 1 + 3
print(result)

In [ ]:
def hello(): # 0 arguments
  print("Hello World!") #  Functions can be used within a function
  # The return clause that defines the return value is optional

hello() # Instead of returning a string, the function itself outputs a string.

<!-- ENG -->
　While `double()`, `plus()`, and `hello()` are functions that we have defined and written ourselves, many functions in Python are pre-defined and called **built-in functions**. `print()` and `range()`, which are already in use, fall into this category.

　The list of built-in functions can be found in [the official Python documentation](https://docs.python.org/ja/3/library/functions.html).

<!-- ENG -->
#### Default argument values

　When using a function, some arguments are often the same, but sometimes you want to enter a different value. In such a case, by specifying the **default value**, you can omit the argument by default and enter it only in special cases.

In [ ]:
def hello(lang='en'):
  if lang=='en':
    print("Hello world!")
  elif lang=='ja':
    print("こんにちは！")
  else:
    print("Undefined language: "+lang)

<!-- ENG -->
If the function is called without giving any argument, it will output English, and if `ja` is passed as the argument `lang`, it will output in Japanese. Other languages are undefined and are output as `"Undefined language: "`. Try actually running it and see.

In [ ]:
hello()

In [ ]:
hello(lang='ja')

In [ ]:
hello('fr') # “lang=” can be omitted

<!-- ENG -->
　Arguments that are not given a default value will **always** require some value to be passed when the function is called, but if they have a default value, the function can be called without specifying anything.

<!-- ENG -->
#### Variable scope
　**Newly defined variables in a function cannot be used outside the function**. The following is an example.

In [ ]:
# Assign 2 to local_variable inside the function
def change():
  local_variable = 2

change()
print(local_variable)

<!-- ENG -->
　The range in which a variable is valid is called the **scope**, and the scope of the `local_variable` indicated above means that it is valid only within the function `change()`. Such variables are also referred to as **local variables**.

　On the other hand, variables defined outside the function have a wider scope and can be referenced from inside and outside the function. Try running the following code.

In [ ]:
def print_a():
  print("From inside: ", a)

a = 1

print_a()
print("From outside:", a)

<!-- ENG -->
　Variables defined outside the function are also called **global variables**, and can be referenced from anywhere. However, global variables are generally avoided because the scope of the variables is so wide that it is difficult to predict when they will be unexpectedly rewritten, and it is easy to overlook variables on which the function depends.

　In this class, we will use arguments for variables used in functions, even if they are global variables.

In [ ]:
def print_a(local_a):
  print("From inside: ", local_a)

a = 1
print_a(a)
print("From outside:", a)

<!-- ENG -->
　Lastly, if there is a global variable and a local variable with the same name, the local variable will be prioritized. Keep in mind that the arguments are also processed as local variables. Run the following code to confirm.

In [ ]:
def print_a(a):
  print("From inside: ", a)
  a += 1
  print("updated a (local variable):", a)

a = 1
print_a(a)
print("From outside:", a)

<!-- ENG -->
As you can see from this behavior, even if the content of the local variable `a` is updated within the `print_a()` function, the content of variable `a` is not updated outside the `print_a()` function, because the global variable `a` is not modified.

--------

<!-- ENG -->
##### Exercise 6 (not required to submit)
　Write your own `var(lst)` function that takes an array and returns the variance as a real number value, and calculate the variance of `lst1` below.

```
lst1 = [8, 2, 4, 0, 5, 6, 0, 5, 6, 3]
```

<!-- ENG -->
For the definition of variance, use the following. $\mu$ indicates the average value of $\boldsymbol{x}$.

$\begin{eqnarray} V = \frac{1}{N} \sum^{N-1}_{i=0}(x_i-\mu)^2 \end{eqnarray}$

--------------

<!-- ENG -->
##### Exercise 7 (Advanced, not required to submit)
　Write your own `median(lst)` function that takes an array with **an odd number** of elements and returns the median, and calculate the median of `lst2` below.

```
lst2 = [5, 3, 2, 5, 7, 10, 10, 5, 0, 9, 3, 1, 6, 6, 0]
```

------

<!-- ENG -->
# Supplementary Material

<!-- ENG -->
## S1 | How to confirm your version of Python

　You can check the version of Python you are currently running in the following way. If you want to set up a Python environment on your own, it is best to use compatible versions.

In [ ]:
import platform
print(platform.python_version())

<!-- ENG -->
## S2 | Summary of common errors

　In programming, it is always a common occurrence to encounter errors. With errors, it is important to observe several frequently occurring errors, because there are cases where the error message is obvious, and cases where it is not obvious what the error is indicating at first glance. Here is a brief summary of the errors that can occur, based on what has been learned so far, thus you can actually run the program and look at them.

1. There is a mix of double byte and single byte spaces
  - **It's difficult to understand the meaning of the errors**. The error message indicates that a double byte space is an "invalid character".
2. Division by zero
3. str + int
4. int + str 
  - Note that the error content is different from 3.
5. Forgetting to add quotation marks when using a string as a `dict` key
  - Note that if you forget to use the string type `str`, it will be treated as a variable name
6. Using the comparison operator `==` and the assignment operator `=`  incorrectly
7. Forgetting the colon (:) in `if` and `for` statements
  - It only tells you that it is invalid syntax, i.e., "syntax is wrong". From where the error is occurring, we need to infer that the colon (:) is missing.
8. Inconsistent indentation in `if` and `for` statements, etc.
9. Forgetting to pass arguments that are required for functions
10. Trying to rewrite a global variable in a function
  - This is not strictly an error, but it is included because it may cause unexpected behavior.
  - Although it is possible to rewrite global variables in functions by using global declarations, this is not recommended in our exercises and has been omitted.

In [ ]:
# 1. There is a mix of double byte and single byte spaces
1 +　2 # There is a double byte space before “2”

In [ ]:
# 2. Division by zero
b = 0
10 / b

In [ ]:
# 3. str + int
1 + "a" # TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
# 4. int + str
"a" + 1 # TypeError: must be str, not int

In [ ]:
# 5. Forgetting to add quotation marks when using a string as a `dict` key
scores = {'Math': 90, 'Science': 75, 'English': 80 }
print(scores["Math"]) # This is correct
print(scores[Math])

In [ ]:
# 6. Using the comparison operator ==  and the assignment operator = incorrectly
if 1 = 2:
  print("One equals two")
else:
  print("One does not equal two")

In [ ]:
# 6. Forgetting the colon (:) in a for statement
for i in [1, 2, 3, 4, 5]
  print(i)

In [ ]:
# 7. Inconsistent indentation in if and for statements, etc.
for i in [1, 2]:
    a = 1       # Four spaces
  print(a + i)  # Two spaces

In [ ]:
# 9. Forgetting to pass arguments that are required for functions
def func(num):
  print(num)

func()

In [ ]:
# 10. Trying to rewrite a global variable in a function

# Since the local variable a is prepared at the moment 
# of assignment to the global variable a in the function func(), 
# it is not possible to rewrite the value of the global variable a in the function.

def func():
  a = 100
  print("From inside: ", a)

a = 1
func()
print("From outside:", a)

<!-- ENG -->
# Sample answers for Exercises

<!-- ENG -->
##### Exercise 1
　This is an exercise to practice arithmetic operators. Execute them as written.

In [ ]:
x = 201
y = 9

print("x + y  =", x + y)
print("x - y  =", x - y)
print("x * y  =", x * y)
print("x / y  =", x / y)
print("x // y =", x // y)
print("x % y  =", x % y)
print("x ** y =", x ** y)

<!-- ENG -->
##### Exercises 2,3
　This is an exercise to practice getting values from list and tuple. Note that a way to obtain vlues is the same between list and tuple.

In [ ]:
# exercise 2

x = (1,5)
y = (5,2)

sq_dist = (x[0] - y[0])**2 + (x[1] - y[1])**2
dist = sq_dist**0.5
print(dist)

In [ ]:
# exercise 3

x = [5, 4, 10, 4]
y = [3, 2, 8, 3]

sq_dist = (x[0] - y[0])**2 + (x[1] - y[1])**2 + (x[2] - y[2])**2 + (x[3] - y[3])**2
dist = sq_dist**0.5
print(dist)

<!-- ENG -->
##### Exercise 4
　This is an exercise to practice `if` statements. To determine whether an integer value is odd or even, divide by 2 to determine the remainder being 1 or 0.

In [ ]:
# Create a random number between 0 and 50
import random
rand_int = random.randint(0, 50)
print(f"rand_int is {rand_int}")

if rand_int%2 == 1:
  print("ODD")
else:
  print("EVEN")

<!-- ENG -->
##### Exercise 5
　It would be best to solve it using `for` statement. If you want to use what you have learned so far, you should use the `range()` function.

In [ ]:
x = [5, 4, 10, 4, 8, 4, 6, 8, 5, 4, 6, 5, 9, 9, 5, 7, 1, 1, 5, 8]
y = [3, 2, 8, 3, 4, 10, 10, 2, 4, 2, 3, 9, 8, 1, 3, 6, 5, 3, 9, 2]

total = 0
for i in range(20):
  xi = x[i]
  yi = y[i]
  total += (xi-yi)**2
print(total**0.5)

<!-- ENG -->
　It can also be written more neatly using the built-in function `zip()`, which is not taught in this course.

In [ ]:
x = [5, 4, 10, 4, 8, 4, 6, 8, 5, 4, 6, 5, 9, 9, 5, 7, 1, 1, 5, 8]
y = [3, 2, 8, 3, 4, 10, 10, 2, 4, 2, 3, 9, 8, 1, 3, 6, 5, 3, 9, 2]

total = 0
for xi, yi in zip(x, y):
  total += (xi-yi)**2
print(total**0.5)

<!-- ENG -->
##### Exercise 6
　This is an example of creating a function. Let's remember that a function is not executed just by defining it. Additionally, following Exercise 5, after defining "variable = 0", it is incremented in the `for` statement, but it is a structure that frequently appears when calculating the sum $\sum$. Let’s keep that in mind.

　Note that `var(lst1)` should be 6.29, but there is a slight error.

In [ ]:
def var(lst):
  mu = sum(lst) / len(lst)
  variance = 0
  for x in lst:
    variance += (x-mu)**2
  return variance / len(lst)

In [ ]:
lst1 = [8, 2, 4, 0, 5, 6, 0, 5, 6, 3]
print(var(lst1))

<!-- ENG -->
　By creating a function, it is possible to calculate the variance as it is even if another array comes in. The following is the case where the variance is 0, which is self-evident.

In [ ]:
lst2 = [3, 3, 3, 3, 3]
print(var(lst2))

<!-- ENG -->
##### Exercise 7
　The median of an odd number of elements is the value of the element exactly in the middle of the sequence (e.g., the third largest/smallest element if there are five elements). The first step is to **rearrange the array in ascending or descending order** and **take the element that is right in the middle**. However, the question is how to take the "element that is right in the middle".

　If we consider the array `lst`, which consists of five elements, the middle element is `lst[2]` (remember that the index starts from 0). It is `lst[3]` if there are seven elements. Generalizing this, we find the following.

　　**The middle element of the array `lst` consisting of 2k + 1 elements is `lst[k]`** 

The shortest way to calculate this is to use floor division `//`. For example, `5 // 2 = 2`, which is consistent with the previous fact.

In [ ]:
def median(lst):
  sorted_lst = sorted(lst)
  center = len(lst)//2
  return sorted_lst[center]

In [ ]:
lst2 = [5, 3, 2, 5, 7, 10, 10, 5, 0, 9, 3, 1, 6, 6, 0]
median(lst2)